glibc: readdir_r is deprecated as of 2.24
On my system (with gcc version 7.2.0) building libutils.a
fails with

    fpga_pci_sysfs.c:394:3: error: ‘readdir_r’ is deprecated [-Werror=deprecated-declarations]