Avoid executing code within error message
The error message was previously running code as opposed to printing an advisory message for the user, which is clearly the intent.

This is how the error message appeared in our logs:

```
/opt/create_sdaccel_afi.sh: line 105: sdaccel_setup.sh: No such file or directory
ERROR: Env variable RELEASE_VER not set, did you ?
```